### ISSUE TITLE
[Feature] Sign Commits and Tags

### ISSUE THREAD

**Issue by kaaax0815** [xchaosmods/Rocket-League-Map-Loader#1]
You can sign your commits and tags with a pgp key, so users instantly can see that e. g. is verified, and not hacked or anything like that. Not necessary, but nice to have.
---
kaaaxcreators.de
Feel free to check out my github

**Comment by xchaosmods** [comment]
Thanks I didn't know that. I'll have a look into that tomorrow 😄

**Comment by kaaax0815** [comment]
No problem, I really like your program, Im a rl player too and always wondered if their is a good manager for that
